//
//  RegisterClasses.swift
//  Fin4teenApp3
//
//  Created by Leonardo Oliveira Portes on 10/06/21.
//


import Foundation


var eDataClasses = [ VideoClasses(sectionTypeClasses: "Introdução sobre Dinheiro",
                                  imageGalleryClasses: ["pairicopaipobre",
                                                        "ossegredosdamente",
                                                        "domilaomilao",
                                                        "ohomemmaisricodababilonia",
                                                        "oinvestidorinteligente",
                                                        "mepoupe","educacaofinanceira",
                                                        "apsicologiafinanceira",
                                                        "comocuidardoseudinheiro",
                                                        "investimentosinteligentes",
                                                        "destraveseudinheiro",
                                                        "quemconvenceenriquece",
                                                        "lucrandocomostubaroes",
                                                        "supersinais",
                                                        "negociandoacoescomfoco",
                                                        "analisetecnicadomercadofin",
                                                        "aboladeneve",
                                                        "facafortunacomacoes",
                                                        "acabecadoinvestidor",
                                                        "ooutroladodabolsa"],
                                  nameClasses: ["Pai Rico, Pai Pobre",
                                                "O Segredo da mente Milionária",
                                                "Do Mil ao Milhão",
                                                "O Homem mais Rico da Babilonia",
                                                "O Investidor Inteligente",
                                                "Me Poupe, O Livro",
                                                "O poder da Educação Financeira",
                                                "A Psicologia Financeira",
                                                "Como cuidar do seu dinheiro",
                                                "Investimentos Inteligentes",
                                                "Destrave seu dinheiro",
                                                "Quem Convence, enriquece!",
                                                "Lucrando com os Tubarões",
                                                "Super Sinais",
                                                "Negociando ações com Foco a longo prazo",
                                                "Analise técnica do mercado financeiro.",
                                                "A Bola de Neve.",
                                                "Faça fortuna Com Ações.",
                                                "A Cabeça do investidor.",
                                                "O outro lado da Bolsa."]),
    
                    VideoClasses(sectionTypeClasses: "Mercado Financeiro",
                                 imageGalleryClasses: ["pairicopaipobre",
                                                       "ossegredosdamente",
                                                       "domilaomilao",
                                                       "ohomemmaisricodababilonia",
                                                       "oinvestidorinteligente",
                                                       "mepoupe","educacaofinanceira",
                                                       "apsicologiafinanceira",
                                                       "comocuidardoseudinheiro",
                                                       "investimentosinteligentes",
                                                       "destraveseudinheiro",
                                                       "quemconvenceenriquece",
                                                       "lucrandocomostubaroes",
                                                       "supersinais",
                                                       "negociandoacoescomfoco",
                                                       "analisetecnicadomercadofin",
                                                       "aboladeneve",
                                                       "facafortunacomacoes",
                                                       "acabecadoinvestidor",
                                                       "ooutroladodabolsa"],
                                 nameClasses: ["Pai Rico, Pai Pobre",
                                               "O Segredo da mente Milionária",
                                               "Do Mil ao Milhão",
                                               "O Homem mais Rico da Babilonia",
                                               "O Investidor Inteligente",
                                               "Me Poupe, O Livro",
                                               "O poder da Educação Financeira",
                                               "A Psicologia Financeira",
                                               "Como cuidar do seu dinheiro",
                                               "Investimentos Inteligentes",
                                               "Destrave seu dinheiro",
                                               "Quem Convence, enriquece!",
                                               "Lucrando com os Tubarões",
                                               "Super Sinais",
                                               "Negociando ações com Foco a longo prazo",
                                               "Analise técnica do mercado financeiro.",
                                               "A Bola de Neve.",
                                               "Faça fortuna Com Ações.",
                                               "A Cabeça do investidor.",
                                               "O outro lado da Bolsa."]),
                     
                     VideoClasses(sectionTypeClasses: "Investimentos",
                                  imageGalleryClasses: ["pairicopaipobre",
                                                        "ossegredosdamente",
                                                        "domilaomilao",
                                                        "ohomemmaisricodababilonia",
                                                        "oinvestidorinteligente",
                                                        "mepoupe","educacaofinanceira",
                                                        "apsicologiafinanceira",
                                                        "comocuidardoseudinheiro",
                                                        "investimentosinteligentes",
                                                        "destraveseudinheiro",
                                                        "quemconvenceenriquece",
                                                        "lucrandocomostubaroes",
                                                        "supersinais",
                                                        "negociandoacoescomfoco",
                                                        "analisetecnicadomercadofin",
                                                        "aboladeneve",
                                                        "facafortunacomacoes",
                                                        "acabecadoinvestidor",
                                                        "ooutroladodabolsa"],
                                  nameClasses: ["Pai Rico, Pai Pobre",
                                                "O Segredo da mente Milionária",
                                                "Do Mil ao Milhão",
                                                "O Homem mais Rico da Babilonia",
                                                "O Investidor Inteligente",
                                                "Me Poupe, O Livro",
                                                "O poder da Educação Financeira",
                                                "A Psicologia Financeira",
                                                "Como cuidar do seu dinheiro",
                                                "Investimentos Inteligentes",
                                                "Destrave seu dinheiro",
                                                "Quem Convence, enriquece!",
                                                "Lucrando com os Tubarões",
                                                "Super Sinais",
                                                "Negociando ações com Foco a longo prazo",
                                                "Analise técnica do mercado financeiro.",
                                                "A Bola de Neve.",
                                                "Faça fortuna Com Ações.",
                                                "A Cabeça do investidor.",
                                                "O outro lado da Bolsa."]),
                     
                     VideoClasses(sectionTypeClasses: "Bolsa de Valores",
                                  imageGalleryClasses: ["pairicopaipobre",
                                                        "ossegredosdamente",
                                                        "domilaomilao",
                                                        "ohomemmaisricodababilonia",
                                                        "oinvestidorinteligente",
                                                        "mepoupe","educacaofinanceira",
                                                        "apsicologiafinanceira",
                                                        "comocuidardoseudinheiro",
                                                        "investimentosinteligentes",
                                                        "destraveseudinheiro",
                                                        "quemconvenceenriquece",
                                                        "lucrandocomostubaroes",
                                                        "supersinais",
                                                        "negociandoacoescomfoco",
                                                        "analisetecnicadomercadofin",
                                                        "aboladeneve",
                                                        "facafortunacomacoes",
                                                        "acabecadoinvestidor",
                                                        "ooutroladodabolsa"],
                                  nameClasses: ["Pai Rico, Pai Pobre",
                                                "O Segredo da mente Milionária",
                                                "Do Mil ao Milhão",
                                                "O Homem mais Rico da Babilonia",
                                                "O Investidor Inteligente",
                                                "Me Poupe, O Livro",
                                                "O poder da Educação Financeira",
                                                "A Psicologia Financeira",
                                                "Como cuidar do seu dinheiro",
                                                "Investimentos Inteligentes",
                                                "Destrave seu dinheiro",
                                                "Quem Convence, enriquece!",
                                                "Lucrando com os Tubarões",
                                                "Super Sinais",
                                                "Negociando ações com Foco a longo prazo",
                                                "Analise técnica do mercado financeiro.",
                                                "A Bola de Neve.",
                                                "Faça fortuna Com Ações.",
                                                "A Cabeça do investidor.",
                                                "O outro lado da Bolsa."]),
                     
                     VideoClasses(sectionTypeClasses: "Criptomoedas",
                                  imageGalleryClasses: ["pairicopaipobre",
                                                        "ossegredosdamente",
                                                        "domilaomilao",
                                                        "ohomemmaisricodababilonia",
                                                        "oinvestidorinteligente",
                                                        "mepoupe",
                                                        "educacaofinanceira",
                                                        "apsicologiafinanceira",
                                                        "comocuidardoseudinheiro",
                                                        "investimentosinteligentes",
                                                        "destraveseudinheiro",
                                                        "quemconvenceenriquece",
                                                        "lucrandocomostubaroes",
                                                        "supersinais",
                                                        "negociandoacoescomfoco",
                                                        "analisetecnicadomercadofin",
                                                        "aboladeneve",
                                                        "facafortunacomacoes",
                                                        "acabecadoinvestidor",
                                                        "ooutroladodabolsa"],
                                  nameClasses: ["Pai Rico, Pai Pobre",
                                                "O Segredo da mente Milionária",
                                                "Do Mil ao Milhão",
                                                "O Homem mais Rico da Babilonia",
                                                "O Investidor Inteligente",
                                                "Me Poupe, O Livro",
                                                "O poder da Educação Financeira",
                                                "A Psicologia Financeira",
                                                "Como cuidar do seu dinheiro",
                                                "Investimentos Inteligentes",
                                                "Destrave seu dinheiro",
                                                "Quem Convence, enriquece!",
                                                "Lucrando com os Tubarões",
                                                "Super Sinais",
                                                "Negociando ações com Foco a longo prazo",
                                                "Analise técnica do mercado financeiro.",
                                                "A Bola de Neve.",
                                                "Faça fortuna Com Ações.",
                                                "A Cabeça do investidor.",
                                                "O outro lado da Bolsa."])]
